name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          global-json-file: "global.json"
          cache: true
          cache-dependency-path: '**/Directory.Packages.props'

      - name: Restore .NET Tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Check vulnerable packages
        run: dotnet list package --vulnerable --include-transitive

      - name: Check format
        run: dotnet format --verify-no-changes --no-restore --severity info

      - name: Build project
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build
